name: Release with mbp file

on: 
  push:
   branches: [master] 

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install maubot
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade maubot
    - name: Build mbp file
      run: mbc build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: latest
        files: |
          *.mbp
